# Generated by Django 3.2.8 on 2021-10-14 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=300)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('video_id', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.CharField(max_length=300)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.comment')),
            ],
        ),
    ]
